### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by 3mora2** [nek0us/ChatGPT#2]
there is way to add login by email and password

**Comment by nek0us** [comment]
I need to wait for a while because I have been busy lately.

**Comment by 3mora2** [comment]
Ok

**Comment by nek0us** [comment]
Thank you for your pr. I added a login other than Apple.

**Comment by 3mora2** [comment]
Base problem is captcha, to solve it we need api.
[Example](https://github.com/nenanopz/openai-captcha-solver)

**Comment by nek0us** [comment]
> Base problem is captcha, to solve it we need api. [Example](https://github.com/nenanopz/openai-captcha-solver)

captcha? Are you referring to cloudflare challenge box, or openai arkose?

**Comment by 3mora2** [comment]
![Screenshot_1](https://github.com/nek0us/ChatGPT/assets/66757189/7548e3e9-1d14-4242-8e30-30a0f511d06a)

when start login in first account show need solve captcha, then it's showing again after 20 or 50 login

**Comment by 3mora2** [comment]
there is way to login within accessToken from `https://chat.openai.com/api/auth/session`

**Comment by nek0us** [comment]
> ![Screenshot_1](https://private-user-images.githubusercontent.com/66757189/293467288-7548e3e9-1d14-4242-8e30-30a0f511d06a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMTc2ODYsIm5iZiI6MTcwNDExNzM4NiwicGF0aCI6Ii82Njc1NzE4OS8yOTM0NjcyODgtNzU0OGUzZTktMWQxNC00MjQyLThlMzAtMzBhMGY1MTFkMDZhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDEzNTYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZmY2ZGQwMTI4NmE3NDlhYmE2NGRkY2Q0NDM0MjY5YjI4ZDg3N2Y3NGZhM2E2MmY0Yzk5ZDA5MGRiNzcwOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VAQdmqtGQToeSspZVeXMXMnklLctheQ5XnAR3c-gIuo)
> 
> when start login in first account show need solve captcha, then it's showing again after 20 or 50 login

Oh, I haven't encountered this situation before. let me take a look.

**Comment by nek0us** [comment]
hey, I also encountered this verification, I added session_token co-login and caching mechanism to reduce the number of direct logins to reduce the possibility of verification

**Comment by 3mora2** [comment]
its nice, please add `stealth_async` to avoid bot detection from cloudflare 
`pip install stealth_async`

```
from playwright.async_api import async_playwright
from playwright_stealth import stealth_async

context = await browser.new_context(service_workers="block")
page = await context.new_page()
await stealth_async(page)
```

**Comment by nek0us** [comment]
> its nice, please add `stealth_async` to avoid bot detection from cloudflare `pip install stealth_async`
> 
> ```
> from playwright.async_api import async_playwright
> from playwright_stealth import stealth_async
> 
> context = await browser.new_context(service_workers="block")
> page = await context.new_page()
> await stealth_async(page)
> ```

ok, added
