### ISSUE TITLE
很好用，如果能支持流式输出就更好了

### ISSUE THREAD

**Issue by sucat1997** [nek0us/ChatGPT#5]
感谢分享

**Comment by nek0us** [comment]
未来添加

**Comment by nek0us** [comment]
暂时命令行里支持了，如果要输出支持需要再开个websocket或者event-stream，或者用生成器重写一遍实现，有点麻烦，精力不够了

**Comment by sucat1997** [comment]
谢谢你的回复，我有一直在关注这个项目，这是个很好的项目，等我研究下。
再次感谢你的分享，并为你的开源精神点赞
